In [1]:
import os

os.environ["DGLBACKEND"] = "pytorch"
import dgl
import numpy as np
import torch

d:\miniconda\envs\torch\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# 1. 用始末节点对来创建DGL图对象

In [2]:
g = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 5]), num_nodes=6)
print(g.edges())

(tensor([0, 1, 2, 3, 4]), tensor([1, 2, 3, 4, 5]))


# 2. 为图对象添加节点和边的特征

In [3]:
# 为所有的边添加名为x的特征，该特征为3维的向量
g.ndata["x"] = torch.randn(6, 3) #NOTE: 第一个维度是节点数
print(g.ndata["x"])

# 添加名为y的特征，该特征为一个张量
g.ndata["y"] = torch.randn(6, 3,5)
print(g.ndata["y"])

# 为边添加特征
g.edata["w"] = torch.randn(5, 2) #NOTE: 第一个维度是边数
print(g.edata["w"])

tensor([[-0.1276, -0.0732, -1.0545],
        [ 0.1000, -0.8473, -0.7076],
        [ 0.2949,  0.6713,  1.0293],
        [-1.0477, -1.3726, -0.2496],
        [-0.1566,  0.8665, -0.0553],
        [-0.1200, -1.6928, -0.4695]])
tensor([[[-0.9795, -1.9189, -0.2174, -0.7226, -0.3734],
         [-1.0780,  1.7245, -0.2887, -0.1209, -0.4703],
         [ 1.8698, -0.9223, -0.5286, -0.1136,  0.4121]],

        [[-0.0623,  0.7058, -0.9261,  1.7798,  0.8032],
         [-0.7016,  0.6724,  0.5253,  1.1716, -0.5839],
         [ 0.9658,  0.3576,  2.4631,  0.2193,  2.2110]],

        [[ 1.3883, -0.2003, -0.0385, -0.5834,  0.6376],
         [ 0.1333, -0.2610,  0.2273, -0.5159, -2.4402],
         [-0.8394,  1.2528,  1.3826, -0.1071, -0.5757]],

        [[-0.5073, -0.3450,  0.2904, -0.1244,  0.6709],
         [-1.3932,  1.3407,  0.3969,  0.7186,  1.7896],
         [-0.7984,  1.0558,  0.6092, -0.3990, -1.0704]],

        [[-0.5573,  1.7067, -0.2591,  0.4231, -0.6546],
         [ 1.7745, -0.7586, -1.1843, -2.5

In [4]:
print(g)

Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(3, 5), dtype=torch.float32)}
      edata_schemes={'w': Scheme(shape=(2,), dtype=torch.float32)})


# 3. 保存和加载DGL图对象

In [ ]:
'''
一个图
'''
dgl.save_graphs('./data/test_save_g.dgl', g)
g1, _ = dgl.load_graphs('./datatest_save_g.dgl',[0])
g1 = g1[0] #

'''
多个图
'''
gg = g.clone()
gg.add_edges([5,6],[6,7]) # 添加边
print(gg) # 
print(gg.ndata["x"]) #NOTE: 可以发现添加后的节点新特征值都是0
dgl.save_graphs('./data/test_save_gg.dgl', [g, gg])
(g2,g3), _ = dgl.load_graphs('./data/test_save_gg.dgl')    

Graph(num_nodes=8, num_edges=7,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(3, 5), dtype=torch.float32)}
      edata_schemes={'w': Scheme(shape=(2,), dtype=torch.float32)})
tensor([[-0.1276, -0.0732, -1.0545],
        [ 0.1000, -0.8473, -0.7076],
        [ 0.2949,  0.6713,  1.0293],
        [-1.0477, -1.3726, -0.2496],
        [-0.1566,  0.8665, -0.0553],
        [-0.1200, -1.6928, -0.4695],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])
